---
title: "Pipeline HMMER"
author: "Jérémy Rousseau"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    number_sections: yes
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Ce document présentes les différents scripts utilisés pour l'analyse HMMER. Par ailleur, les scritps ont été exécuté sur les clusters de calucl du Museum National d'Hitoire Narurel (PCIA) et de celui de la Sorbonne Université (SACADO).

Les différents paramètres utilisé pour les scripts sont présenté dans le dossier *param_cluster*.

# Préparation des données

## Supression des caractères

A la fin de certaines séquence, il y a un "\*" à la fin de certaines séquences. Afin de permettre l'analyse avec HMMER, il faut les supprimers. Pour cela, nous utilisont le script **_removing\_special\_character.sh_** 

```{bash removing_special_characters, eval=FALSE}
#!/bin/bash

cd /scratchbeta/rousseau/Tara_Ocean

sed 's/\*//g' SMAGs_v1_concat.faa > SMAGs.faa
```

### Fichier d'entrée

Le fichier d'entrée contient la totalité de séquence protéique.

### Fichier de sortie

Le fichier de sortie contient les séquences séquences protéiques filtrées.

## Séparation du jeu de données

Le jeu de données initiale (*SMAGs_v1_concat.faa*) contenant 10207435 séquences, la première étape à été de le séparer en plusieurs fichiers contenant chacun 100000 séquences afin de ppuvoir effectuer plusieurs analyse en même temps. Nous utilisons le scipt **_split\_multifasta.sh_**

```{bash split_multifasta, eval=FALSE}
#!/bin/bash

cd /scratchbeta/rousseau/Tara_Ocean

touch data1.faa # premie fichier

count=0
NbData=1

while read line
do

if [[ ${line:0:1} == '>' ]]
then

if [ $count -ge 100000 ] # chaque fichier contient 100000 séquences
then
count=0
let "NbData++" 
fi

let "count++"
echo $line >> data$NbData.faa

else
echo $line >> data$NbData.faa

fi

done < SMAGs.faa
```

### FIchiers d'entrées

Ce script prend en entrée le fichier contenant la totalité des séquences protéiques filtré grace au script précédent.

### Fichiers de sorties

Ce script permet de générer plusieurs dossier contenant chacun 100000 séquences. Dans le cas de cette analyse, il y a 103 fichiers qui ont été génré.

# Analyse HMMER

HMMER est un logiciel open source, disponible sur : [http://hmmer.org/](http://hmmer.org/). Il comprend diverse outils qui peuvent, par exemple, être utilisés pour l'analyse de profils HMM des séquences protéiques. Dans notre étude, nous avons utilisé l'outil hmmsearch, cet outils permet de rechercher le profil HMM d'une séquence dans une base de données. Dans notre cas, nous avons utilisé Gene3D - base de données de CATH.

Guide d'utilisation HMMER : [http://eddylab.org/software/hmmer/Usergude.pdf](http://eddylab.org/software/hmmer/Usergude.pdf).

Le programme HMMER a donc été utilisé avec le script *hmmer.sh*.

```{bash HMMER, eval=FALSE}

#!/bin/bash

cd /scratchbeta/rousseau

date

echo "Start HMMER"
#run hmmsearch on sequence file, change parameters as appropriate
hmmsearch -Z 10000000 --domE 0.001 --incdomE 0.001 -o Tara_Ocean/data?.hmmsearch gene3d_hmmsearch/hmms/main.hmm Tara_Ocean/data?.faa

echo "Start cath-resolved_hit"
#resolve any conflicting (overlapping) domain assignments, versions for different platforms (mac/linux) are available online along with documentation:
# http://cath-tools.readthedocs.io/en/latest/tools/cath-resolve-hits/
# we recommend using a worst-permissible-bitscore of 25 and applying --min-dc-hmm-coverage=80 (only available for processing hmmsearch output) 
./gene3d_hmmsearch/cath-resolve-hits --min-dc-hmm-coverage=80 --worst-permissible-bitscore 25 --output-hmmer-aln --input-format hmmsearch_out Tara_Ocean/data?.hmmsearch > Tara_Ocean/data?.crh

echo "Start assign-cath-superfamily"
#assign CATH superfamilies to the output file generated by cath-resolve-hits
python ./gene3d_hmmsearch/assign_cath_superfamilies.py Tara_Ocean/data?.crh

echo -e "\nEnd analysis with HMMER\n"

```

Les "?" sotn remplacer par le numéro du ficheir d'entrée, ce référer au fichier concernant l'éxécution des scripts *hmmer.sh* et *check_sequences.sh*.

## Paramètres et fichiers d'entrés

Les paramètres utilisés pour l'analyses HMMER son ceux indiqué par Gene3D. Ainsi, hmmsearch prend plusieurs paramètres pour effectuer l'analyse :

  * **-Z** : cette option définit la taille de l'espace de recherche\
  * **-domE** : cette option permet d'indiquer une E-value condition <= x qui corespond au d'inclusion du domaine. Elle s'applique au données qui ont dépassé le sueil d'inclusion global (la valeur par défaut est 0.01)\
  * **-incdomE** : cette option s'applique aux séquences qui ont déjà un profil HMM. Nous pouvons donner une valeur E conditionnelle <= x (la valeur par défaut est 10). La valeur E est utilisée pour indiquer le nombre de faux positifs supplémentaires dans le plus petit espace de recherche\
  * **-o** : permet d'indiquer le fichier de sortie (.hmmsearch) où se trouveront les profils HMM, la base de données Gene3D (CATH) et le fichier d'entrée contenant les séquences protéiques
  
cath-resolve-hits est un programme présent avec la base de données Gene3D. Le programme hmmsearch fournit des données brutes, mais il ne tient pas compte du chevauchement entre les domaines. Pour prendre en compte ce chevauchement, nous utilisons le programme cath-resolved-hits : [https://cath-tools.readthedocs.io/en/latest/tools/cath-resolve-hits/#cath-resolve-hits](cath-tools.readthedocs.io/en/latest/tools/cath-resolve-hits/#cath-resolve-hits).

Ce programme prend plusieurs paramètre :

  * **–min-dc–hmm-coverage=80**\
  * **–worst-permissible-bitscore 25**\
  * **–output-hmmer-aln**\
  * **–input-format hmmsearch_out**

Le programme *assign_cath_superfamilies.py* (codé en python python2) est utilisé pour attribuer à chaque domaine CATH détecté son groupe de superfamilles homologue. Il prend en entré le fichier généré par le programme *cath-resolved-hits*.

## Fchiers de sorties

Ce script génère 3 fichier :

  * **file_name.hmmsearch** : ficher généré par le programme hmmsearch\
  * **file_name.crh** : fichier généré par le programme cath-resolved-hits\
  * **file_name.crh.csv** : fichier généré par le programme assign-cath-superfamies.py
  
# Recherhce des séquences connus et inconnus

Le programme hmmsearch ne permet pas d'obtenir un fichier contenant les séquences qui n'ont pas otenus de profil HMM. Pour cela, il faut reagarder pour chaque séquence du ficheir .faa si elle est présente dans le tableau .crh.csv. Si la séquence est présente au moin une fois dans le tableau c'est quelle présente un profil HMM. Au contraire, si la séquence n'est pas présente dans le tableau onous pouvons la considérer comme étant inconnus. Pour vérifier cela nous avons utilisé le script *check_sequences.sh*.

```{bash check_sequence, eval=FALSE}
#!/bin/bash

cd /scratchbeta/rousseau/Tara_Ocean

date

mkdir sequence_known
mkdir sequence_unknown

touch sequence_known/sequence_known_?.faa
touch sequence_unknown/sequence_unknown_?.faa

while read line
do

if [[ ${line:0:1} == '>' ]]
then
echo ${line:1:$((${#line}-0))} > temporary_file_?.txt
IDline=`cat temporary_file_?.txt`

grep $IDline data?.crh.csv > res_grep_?.txt

if [ -s res_grep_?.txt ]
then
outfile=sequence_known/sequence_known_?.faa
echo $line >> $outfile
#echo $outfile
else
outfile=sequence_unknown/sequence_unknown_?.faa
echo $line >> $outfile
#echo $outfile
fi

else
echo $line >> $outfile

fi

done < data?.faa

rm -f temporary_file_?.txt
rm -f res_grep_?.txt

date
```

Les "?" sotn remplacer par le numéro du ficheir d'entrée, ce référer au fichier concernant l'éxécution des scripts *hmmer.sh* et *check_sequences.sh*, dans le.

## Fichiers d'entrées

Ce script prend en entré deux fichiers. Tous d'abord le fichier .faa contenant les séquences protéiques, ainsi que le fichier .crh.csv correspond, contenant les résultat d'HMMER.

## Fichier de sorties

Ce script génère deux fichiers temporaires qui sont supprimés à l fin de l'analyse :

  * **temporary_file.txt** : il contient l'identifiant de chaque séquence\
  * **res_grep.txt** : ce fichier contient les informations présent dans le tableau .crh.csv, ce ficheir est vide s'il n'y a aucune information concernant la séquence.

Ce script génère aussi deux autres fichiers :

   * **sequence_known.faa** : fichier qui contient la totalité des séquences connus détecté avec hmmsearch\
   * **sequence_unknown.faa** : fichier qui contient la totalité des séquences inconnus\


   
  


